### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by CharlieNoodl** [JohannesKlauss/storybook-workshop#53]
Hi !

I have been taking a look at your project and it looks great ! I noticed it is well tested so kudos for that ! However, I found some vulnerabilities in your testsuite that I would like to share with you:
- First, reportWebVitals.js files should always be tested
- Second, your useDeleteTodo file could get some more tests
- Finally, do not hesitate to test your ui elements

I am working on a project called Ponicode, it is a VS Code extension that writes AI-generated unit tests. I think it could help you test your projects quickly.
It would be awesome if you could check it out on the VS Code Market Place (https://marketplace.visualstudio.com/items?itemName=ponicode.ponicode) and I would love to have some feedback.

Have a nice day,

Charlie.

**Comment by JohannesKlauss** [comment]
This is a base repo for a workshop I gave, please refrain from advertising.
